module.exports = {
  printWidth: 120,
  useTabs: false,
  tabWidth: 2,
  semi: false,
  bracketSpacing: true,
  endOfLine: 'auto',
  htmlWhitespaceSensitivity: 'ignore',
  jsxBracketSameLine: true,
  bracketSameLine: true,
  singleQuote: true,
  trailingComma: 'es5',
  importOrder: [
    '^(react/(.*)$)|^(react$)',
    '<THIRD_PARTY_MODULES>',
    '',
    '^types$',
    '^@/__mock__/(.*)$',
    '^@/context/(.*)$',
    '^@/types/(.*)$',
    '^@/constants/(.*)$',
    '^@/utils/(.*)$',
    '^@/hooks/(.*)$',
    '^@/state/(.*)$',
    '^@/components/(.*)$',
    '^@/routes/(.*)$',
    '^@/assets/(.*)$',
    '',
    '^[./]',
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ['@ianvs/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
}
